joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

wheel_fl_wheel_controller: {type: effort_controllers/JointVelocityController, joint: wheel_fl_wheel_joint, pid: {p: 6.0, i: 0.0, d: 0.2}}
wheel_fr_wheel_controller: {type: effort_controllers/JointVelocityController, joint: wheel_fr_wheel_joint, pid: {p: 6.0, i: 0.0, d: 0.2}}
wheel_ml_wheel_controller: {type: effort_controllers/JointVelocityController, joint: wheel_ml_wheel_joint, pid: {p: 6.0, i: 0.0, d: 0.2}}
wheel_mr_wheel_controller: {type: effort_controllers/JointVelocityController, joint: wheel_mr_wheel_joint, pid: {p: 6.0, i: 0.0, d: 0.2}}
wheel_rl_wheel_controller: {type: effort_controllers/JointVelocityController, joint: wheel_rl_wheel_joint, pid: {p: 6.0, i: 0.0, d: 0.2}}
wheel_rr_wheel_controller: {type: effort_controllers/JointVelocityController, joint: wheel_rr_wheel_joint, pid: {p: 6.0, i: 0.0, d: 0.2}}

wheel_fl_steer_controller: {type: effort_controllers/JointPositionController, joint: wheel_fl_steer_joint, pid: {p: 40.0, i: 0.0, d: 2.0}}
wheel_fr_steer_controller: {type: effort_controllers/JointPositionController, joint: wheel_fr_steer_joint, pid: {p: 40.0, i: 0.0, d: 2.0}}
wheel_rl_steer_controller: {type: effort_controllers/JointPositionController, joint: wheel_rl_steer_joint, pid: {p: 40.0, i: 0.0, d: 2.0}}
wheel_rr_steer_controller: {type: effort_controllers/JointPositionController, joint: wheel_rr_steer_joint, pid: {p: 40.0, i: 0.0, d: 2.0}}

joint1_link_controller: {type: effort_controllers/JointPositionController, joint: joint1_link_joint, pid: {p: 80.0, i: 0.0, d: 4.0}}
joint2_link_controller: {type: effort_controllers/JointPositionController, joint: joint2_link_joint, pid: {p: 80.0, i: 0.0, d: 4.0}}
joint3_link_controller: {type: effort_controllers/JointPositionController, joint: joint3_link_joint, pid: {p: 80.0, i: 0.0, d: 4.0}}
joint4_link_controller: {type: effort_controllers/JointPositionController, joint: joint4_link_joint, pid: {p: 60.0, i: 0.0, d: 3.0}}
joint5_link_controller: {type: effort_controllers/JointPositionController, joint: joint5_link_joint, pid: {p: 60.0, i: 0.0, d: 3.0}}
