base:
  length: 0.90
  width: 0.60
  height: 0.20
  mass: 30.0

wheels:
  radius: 0.12
  width: 0.06
  track_width: 0.55
  wheelbase: 0.75
  z_offset: 0.12

arm_mount:
  x: 0.35
  y: 0.0
  z: 0.25

arm:
  l1: 0.12
  l2: 0.18
  l3: 0.20
  l4: 0.10
  l5: 0.07

arm_limits:
  j1: [-3.14, 3.14]
  j2: [-1.57, 1.57]
  j3: [-1.57, 1.57]
  j4: [-2.2, 2.2]
  j5: [-2.2, 2.2]
