joint_limits:
  joint1_link_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 2.0

  joint2_link_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.5

  joint3_link_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.5

  joint4_link_joint:
    has_position_limits: true
    min_position: -2.2
    max_position: 2.2
    has_velocity_limits: true
    max_velocity: 2.0

  joint5_link_joint:
    has_position_limits: true
    min_position: -2.2
    max_position: 2.2
    has_velocity_limits: true
    max_velocity: 2.0
