planning_pipelines:
  pipelines: ["ompl"]

ompl:
  planning_plugins:
    - ompl_interface/OMPLPlanner

  planner_configs:
    RRTConnect:
      type: geometric::RRTConnect
      range: 0.1

  request_adapters:
    - default_planning_request_adapters/AddTimeOptimalParameterization
    - default_planning_request_adapters/FixWorkspaceBounds
    - default_planning_request_adapters/FixStartStateBounds
    - default_planning_request_adapters/FixStartStateCollision
    - default_planning_request_adapters/FixStartStatePathConstraints

  start_state_max_bounds_error: 0.1
